// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: packages/proto/risk.proto

package risk

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderSide int32

const (
	OrderSide_ORDER_SIDE_UNSPECIFIED OrderSide = 0
	OrderSide_ORDER_SIDE_BUY         OrderSide = 1
	OrderSide_ORDER_SIDE_SELL        OrderSide = 2
)

// Enum value maps for OrderSide.
var (
	OrderSide_name = map[int32]string{
		0: "ORDER_SIDE_UNSPECIFIED",
		1: "ORDER_SIDE_BUY",
		2: "ORDER_SIDE_SELL",
	}
	OrderSide_value = map[string]int32{
		"ORDER_SIDE_UNSPECIFIED": 0,
		"ORDER_SIDE_BUY":         1,
		"ORDER_SIDE_SELL":        2,
	}
)

func (x OrderSide) Enum() *OrderSide {
	p := new(OrderSide)
	*p = x
	return p
}

func (x OrderSide) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderSide) Descriptor() protoreflect.EnumDescriptor {
	return file_packages_proto_risk_proto_enumTypes[0].Descriptor()
}

func (OrderSide) Type() protoreflect.EnumType {
	return &file_packages_proto_risk_proto_enumTypes[0]
}

func (x OrderSide) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderSide.Descriptor instead.
func (OrderSide) EnumDescriptor() ([]byte, []int) {
	return file_packages_proto_risk_proto_rawDescGZIP(), []int{0}
}

type CheckAndLockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParticipantId string                 `protobuf:"bytes,1,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Side          OrderSide              `protobuf:"varint,3,opt,name=side,proto3,enum=risk.OrderSide" json:"side,omitempty"`
	Quantity      int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         int64                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAndLockRequest) Reset() {
	*x = CheckAndLockRequest{}
	mi := &file_packages_proto_risk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAndLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAndLockRequest) ProtoMessage() {}

func (x *CheckAndLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packages_proto_risk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAndLockRequest.ProtoReflect.Descriptor instead.
func (*CheckAndLockRequest) Descriptor() ([]byte, []int) {
	return file_packages_proto_risk_proto_rawDescGZIP(), []int{0}
}

func (x *CheckAndLockRequest) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

func (x *CheckAndLockRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CheckAndLockRequest) GetSide() OrderSide {
	if x != nil {
		return x.Side
	}
	return OrderSide_ORDER_SIDE_UNSPECIFIED
}

func (x *CheckAndLockRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CheckAndLockRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type CheckAndLockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Approved      bool                   `protobuf:"varint,1,opt,name=approved,proto3" json:"approved,omitempty"`
	LockId        string                 `protobuf:"bytes,2,opt,name=lock_id,json=lockId,proto3" json:"lock_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAndLockResponse) Reset() {
	*x = CheckAndLockResponse{}
	mi := &file_packages_proto_risk_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAndLockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAndLockResponse) ProtoMessage() {}

func (x *CheckAndLockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packages_proto_risk_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAndLockResponse.ProtoReflect.Descriptor instead.
func (*CheckAndLockResponse) Descriptor() ([]byte, []int) {
	return file_packages_proto_risk_proto_rawDescGZIP(), []int{1}
}

func (x *CheckAndLockResponse) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *CheckAndLockResponse) GetLockId() string {
	if x != nil {
		return x.LockId
	}
	return ""
}

func (x *CheckAndLockResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ReleaseLockRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LockId         string                 `protobuf:"bytes,1,opt,name=lock_id,json=lockId,proto3" json:"lock_id,omitempty"`
	FilledQuantity int64                  `protobuf:"varint,2,opt,name=filled_quantity,json=filledQuantity,proto3" json:"filled_quantity,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReleaseLockRequest) Reset() {
	*x = ReleaseLockRequest{}
	mi := &file_packages_proto_risk_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseLockRequest) ProtoMessage() {}

func (x *ReleaseLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packages_proto_risk_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseLockRequest.ProtoReflect.Descriptor instead.
func (*ReleaseLockRequest) Descriptor() ([]byte, []int) {
	return file_packages_proto_risk_proto_rawDescGZIP(), []int{2}
}

func (x *ReleaseLockRequest) GetLockId() string {
	if x != nil {
		return x.LockId
	}
	return ""
}

func (x *ReleaseLockRequest) GetFilledQuantity() int64 {
	if x != nil {
		return x.FilledQuantity
	}
	return 0
}

type ReleaseLockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Released      bool                   `protobuf:"varint,1,opt,name=released,proto3" json:"released,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseLockResponse) Reset() {
	*x = ReleaseLockResponse{}
	mi := &file_packages_proto_risk_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseLockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseLockResponse) ProtoMessage() {}

func (x *ReleaseLockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packages_proto_risk_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseLockResponse.ProtoReflect.Descriptor instead.
func (*ReleaseLockResponse) Descriptor() ([]byte, []int) {
	return file_packages_proto_risk_proto_rawDescGZIP(), []int{3}
}

func (x *ReleaseLockResponse) GetReleased() bool {
	if x != nil {
		return x.Released
	}
	return false
}

var File_packages_proto_risk_proto protoreflect.FileDescriptor

const file_packages_proto_risk_proto_rawDesc = "" +
	"\n" +
	"\x19packages/proto/risk.proto\x12\x04risk\"\xab\x01\n" +
	"\x13CheckAndLockRequest\x12%\n" +
	"\x0eparticipant_id\x18\x01 \x01(\tR\rparticipantId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12#\n" +
	"\x04side\x18\x03 \x01(\x0e2\x0f.risk.OrderSideR\x04side\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantity\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x03R\x05price\"c\n" +
	"\x14CheckAndLockResponse\x12\x1a\n" +
	"\bapproved\x18\x01 \x01(\bR\bapproved\x12\x17\n" +
	"\alock_id\x18\x02 \x01(\tR\x06lockId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"V\n" +
	"\x12ReleaseLockRequest\x12\x17\n" +
	"\alock_id\x18\x01 \x01(\tR\x06lockId\x12'\n" +
	"\x0ffilled_quantity\x18\x02 \x01(\x03R\x0efilledQuantity\"1\n" +
	"\x13ReleaseLockResponse\x12\x1a\n" +
	"\breleased\x18\x01 \x01(\bR\breleased*P\n" +
	"\tOrderSide\x12\x1a\n" +
	"\x16ORDER_SIDE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eORDER_SIDE_BUY\x10\x01\x12\x13\n" +
	"\x0fORDER_SIDE_SELL\x10\x022\x98\x01\n" +
	"\vRiskService\x12E\n" +
	"\fCheckAndLock\x12\x19.risk.CheckAndLockRequest\x1a\x1a.risk.CheckAndLockResponse\x12B\n" +
	"\vReleaseLock\x12\x18.risk.ReleaseLockRequest\x1a\x19.risk.ReleaseLockResponseB*Z(github.com/YHQZ1/esx/packages/proto/riskb\x06proto3"

var (
	file_packages_proto_risk_proto_rawDescOnce sync.Once
	file_packages_proto_risk_proto_rawDescData []byte
)

func file_packages_proto_risk_proto_rawDescGZIP() []byte {
	file_packages_proto_risk_proto_rawDescOnce.Do(func() {
		file_packages_proto_risk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packages_proto_risk_proto_rawDesc), len(file_packages_proto_risk_proto_rawDesc)))
	})
	return file_packages_proto_risk_proto_rawDescData
}

var file_packages_proto_risk_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_packages_proto_risk_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_packages_proto_risk_proto_goTypes = []any{
	(OrderSide)(0),               // 0: risk.OrderSide
	(*CheckAndLockRequest)(nil),  // 1: risk.CheckAndLockRequest
	(*CheckAndLockResponse)(nil), // 2: risk.CheckAndLockResponse
	(*ReleaseLockRequest)(nil),   // 3: risk.ReleaseLockRequest
	(*ReleaseLockResponse)(nil),  // 4: risk.ReleaseLockResponse
}
var file_packages_proto_risk_proto_depIdxs = []int32{
	0, // 0: risk.CheckAndLockRequest.side:type_name -> risk.OrderSide
	1, // 1: risk.RiskService.CheckAndLock:input_type -> risk.CheckAndLockRequest
	3, // 2: risk.RiskService.ReleaseLock:input_type -> risk.ReleaseLockRequest
	2, // 3: risk.RiskService.CheckAndLock:output_type -> risk.CheckAndLockResponse
	4, // 4: risk.RiskService.ReleaseLock:output_type -> risk.ReleaseLockResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_packages_proto_risk_proto_init() }
func file_packages_proto_risk_proto_init() {
	if File_packages_proto_risk_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packages_proto_risk_proto_rawDesc), len(file_packages_proto_risk_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_packages_proto_risk_proto_goTypes,
		DependencyIndexes: file_packages_proto_risk_proto_depIdxs,
		EnumInfos:         file_packages_proto_risk_proto_enumTypes,
		MessageInfos:      file_packages_proto_risk_proto_msgTypes,
	}.Build()
	File_packages_proto_risk_proto = out.File
	file_packages_proto_risk_proto_goTypes = nil
	file_packages_proto_risk_proto_depIdxs = nil
}
