// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: packages/proto/participant.proto

package participant

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateAPIKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAPIKeyRequest) Reset() {
	*x = ValidateAPIKeyRequest{}
	mi := &file_packages_proto_participant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAPIKeyRequest) ProtoMessage() {}

func (x *ValidateAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packages_proto_participant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*ValidateAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_packages_proto_participant_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateAPIKeyRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type ValidateAPIKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParticipantId string                 `protobuf:"bytes,1,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsActive      bool                   `protobuf:"varint,3,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAPIKeyResponse) Reset() {
	*x = ValidateAPIKeyResponse{}
	mi := &file_packages_proto_participant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAPIKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAPIKeyResponse) ProtoMessage() {}

func (x *ValidateAPIKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packages_proto_participant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAPIKeyResponse.ProtoReflect.Descriptor instead.
func (*ValidateAPIKeyResponse) Descriptor() ([]byte, []int) {
	return file_packages_proto_participant_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateAPIKeyResponse) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

func (x *ValidateAPIKeyResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ValidateAPIKeyResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

var File_packages_proto_participant_proto protoreflect.FileDescriptor

const file_packages_proto_participant_proto_rawDesc = "" +
	"\n" +
	" packages/proto/participant.proto\x12\vparticipant\"0\n" +
	"\x15ValidateAPIKeyRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\"p\n" +
	"\x16ValidateAPIKeyResponse\x12%\n" +
	"\x0eparticipant_id\x18\x01 \x01(\tR\rparticipantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tis_active\x18\x03 \x01(\bR\bisActive2o\n" +
	"\x12ParticipantService\x12Y\n" +
	"\x0eValidateAPIKey\x12\".participant.ValidateAPIKeyRequest\x1a#.participant.ValidateAPIKeyResponseB1Z/github.com/YHQZ1/esx/packages/proto/participantb\x06proto3"

var (
	file_packages_proto_participant_proto_rawDescOnce sync.Once
	file_packages_proto_participant_proto_rawDescData []byte
)

func file_packages_proto_participant_proto_rawDescGZIP() []byte {
	file_packages_proto_participant_proto_rawDescOnce.Do(func() {
		file_packages_proto_participant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packages_proto_participant_proto_rawDesc), len(file_packages_proto_participant_proto_rawDesc)))
	})
	return file_packages_proto_participant_proto_rawDescData
}

var file_packages_proto_participant_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_packages_proto_participant_proto_goTypes = []any{
	(*ValidateAPIKeyRequest)(nil),  // 0: participant.ValidateAPIKeyRequest
	(*ValidateAPIKeyResponse)(nil), // 1: participant.ValidateAPIKeyResponse
}
var file_packages_proto_participant_proto_depIdxs = []int32{
	0, // 0: participant.ParticipantService.ValidateAPIKey:input_type -> participant.ValidateAPIKeyRequest
	1, // 1: participant.ParticipantService.ValidateAPIKey:output_type -> participant.ValidateAPIKeyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_packages_proto_participant_proto_init() }
func file_packages_proto_participant_proto_init() {
	if File_packages_proto_participant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packages_proto_participant_proto_rawDesc), len(file_packages_proto_participant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_packages_proto_participant_proto_goTypes,
		DependencyIndexes: file_packages_proto_participant_proto_depIdxs,
		MessageInfos:      file_packages_proto_participant_proto_msgTypes,
	}.Build()
	File_packages_proto_participant_proto = out.File
	file_packages_proto_participant_proto_goTypes = nil
	file_packages_proto_participant_proto_depIdxs = nil
}
